<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/16
 * Time: 20:14
 */

namespace app\mobile\controller;

use think\Lang;

class Memberaccount extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Lang::load(APP_PATH . 'home/lang/' . config('default_lang') . '/memberpoints.lang.php');
    }

    /**
     * 初次绑定手机第一步
     */
    public function bind_mobile_step1()
    {
        if (!$_POST['mobile'] || !preg_match('/^\d{11}$/', $_POST['mobile'])) {
            output_error('请正确输入手机号',['code'=>'']);
        }
       /* if (!preg_match('/^\w{4}$/', $_POST['captcha']) || !captcha_check($_POST['captcha'])) {
            output_error('验证码错误',['code'=>'']);
        }*/

        $model_member = Model('member');
        $check_mobile = $model_member->getMemberInfo(array(
                                                         'member_mobile' => trim($_POST['mobile']),
                                                         'member_mobilebind' => 1
                                                     ));
        if (is_array($check_mobile) and count($check_mobile) > 0) {
            output_error('手机号码已经被绑定过',['code'=>'']);
        }
        //发送频率验证
        $member_common_info = $model_member->getMemberCommonInfo(array('member_id' => $this->member_info['member_id']));
        if (!empty($member_common_info['send_acode_time'])) {
            if (date('Ymd', $member_common_info['send_acode_time']) != date('Ymd', TIMESTAMP)) {
                $data = array();
                $data['send_acode_times'] = 0;
                $update = $model_member->editMemberCommon($data, array('member_id' => $this->member_info['member_id']));
            }
            else {
                if (TIMESTAMP - $member_common_info['send_acode_time'] < DEFAULT_CONNECT_SMS_TIME) {
                    output_error('请60秒以后再发',['code'=>'']);
                }
                else {
                    if ($member_common_info['send_acode_times'] >= 15) {
                        output_error('今天短信已超15条，无法发送',['code'=>'']);
                    }
                }
            }
        }

        try {
            $verify_code = rand(100, 999) . rand(100, 999);
            $tpl_info = Model('mailtemplates')->getTplInfo(array('code' => 'authenticate'));
            $param = array();
            $param['send_time'] = date('Y-m-d H:i', TIMESTAMP);
            $param['verify_code'] = $verify_code;
            $param['site_name'] = config('site_name');
            $message = ncReplaceText($tpl_info['content'], $param);
            $sms = new \sendmsg\Sms();
            $result = $sms->send($_POST['mobile'], $message);
            if ($result) {
                $data = array();
                $update_data['auth_code'] = $verify_code;
                $update_data['send_acode_time'] = TIMESTAMP;
                $update_data['send_acode_times'] = array('exp', 'send_acode_times+1');
                $update = $model_member->editMemberCommon($update_data, array('member_id' => $this->member_info['member_id']));
                if (!$update) {
                    output_error('系统发生错误1');
                }
                $updates = array();
                $updates['member_mobile'] = $_POST['mobile'];
                $model_member->editMember(array('member_id' => $this->member_info['member_id']),$updates);
                output_data(array('sms_time' => DEFAULT_CONNECT_SMS_TIME));
            }
            else {
                output_error('验证码发送失败');
            }
        } catch (Exception $e) {
            output_error($e->getMessage());
        }
    }

    /**
     * 初次绑定手机第二步 - 验证短信码
     */
    public function bind_mobile_step2()
    {
        if (!$_POST['auth_code'] || !preg_match('/^\d{6}$/', $_POST['auth_code'])) {
            output_error('请正确输入短信验证码',['code'=>'-1']);
        }
        $model_member = Model('member');
        $member_common_info = $model_member->getMemberCommonInfo(array('member_id' => $this->member_info['member_id']));
        if (empty($member_common_info) || !is_array($member_common_info)) {
            output_error('验证失败',['code'=>'-1']);
        }
        if (TIMESTAMP - $member_common_info['send_acode_time'] > 1800) {
            output_error('验证码已失效，请重新获取',['code'=>'-1']);
        }
        if ($member_common_info['auth_code_check_times'] > 3) {
            output_error('输入错误次数过多，请重新获取',['code'=>'-1']);
        }
        if ($member_common_info['auth_code'] != $_POST['auth_code']) {
            $data = array();
            $update_data['auth_code_check_times'] = array('exp', 'auth_code_check_times+1');
            $update = $model_member->editMemberCommon($update_data, array('member_id' => $this->member_info['member_id']));
            if (!$update) {
                output_error('系统发生错误',['code'=>'-1']);
            }
            output_error('验证失败',['code'=>'-1']);
        }

        $data = array();
        $data['auth_code'] = '';
        $data['send_acode_time'] = 0;
        $data['auth_code_check_times'] = 0;
        $update = $model_member->editMemberCommon($data, array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误');
        }
        $updates = array();
        $updates['member_mobilebind'] =1;
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']),$updates);
        if (!$update) {
            output_error('系统发生错误');
        }
        output_data('1');
    }

    /**
     * 检测会员手机是否绑定
     * 更改绑定手机 第一步 - 得到已经绑定的手机号
     * 修改密码 第一步 - 得到已经绑定的手机号
     * 修改支付密码 第一步 - 得到已经绑定的手机号
     */
    public function get_mobile_info()
    {
        $data = array();
        $data['state'] = $this->member_info['member_mobilebind'] ? true : false;
        $data['mobile'] = $data['state'] ? encrypt_show($this->member_info['member_mobile'], 4, 4) : $this->member_info['member_mobile'];
        output_data($data);
    }

    /**
     * 检测是否设置了支付密码
     */
    public function get_paypwd_info()
    {
        $data = array();
        $data['state'] = $this->member_info['member_paypwd'] ? true : false;
        output_data($data);
    }

    /**
     * 更改绑定手机 第二步 - 向已经绑定的手机发送验证码
     */
    public function modify_mobile_step2()
    {
        $this->_send_bind_mobile_msg();
    }

    /**
     * 更改密码 第二步 - 向已经绑定的手机发送验证码
     */
    public function modify_password_step2()
    {
        $this->_send_bind_mobile_msg();
    }

    /**
     * 更改支付密码
     * @DateTime 2019-12-02
     * @return   [type]     [description]
     */
    public function modify_paypwd_step2()
    {   

        $this->_send_bind_mobile_msg();
    }

    private function _send_bind_mobile_msg()
    {
        $type = input('param.type','mobile');
        $captch=input('param.captcha');
        if(!captcha_check($captch)){
           output_error('图片验证码错误');
        }
        
        $member_model = model('member');
        $member_info = $member_model->getMemberInfoByID($this->member_info['member_id']);


        //验证发送频率
        $verify_code_model = model('verify_code');
        $result = $verify_code_model->isVerifyCodeFrequant(6, 1);
        if (!$result['code']) {
            output_error($result['msg']);
        }

        $verify_code = $verify_code_model->genVerifyCode(6, 1);
        if (!$verify_code) {
            output_error(lang('system_error'));
        }
        $mailtemplates_model = model('mailtemplates');
        $tpl_info = $mailtemplates_model->getTplInfo(array('mailmt_code' => 'authenticate'));

        $param = array();
        $param['send_time'] = date('Y-m-d H:i', TIMESTAMP);
        $param['verify_code'] = $verify_code;
        $param['site_name'] = config('site_name');
        $subject = ds_replace_text($tpl_info['mailmt_title'], $param);
        $message = ds_replace_text($tpl_info['mailmt_content'], $param);

        if ($type == 'email') {
            $email = new \sendmsg\Email();
            $result['state'] = $email->send_sys_email($member_info["member_email"], $subject, $message);
        } elseif ($type == 'mobile') {
            $result = model('smslog')->sendSms($member_info["member_mobile"], $message,5,$verify_code);
        }

        if ($result['state']) {
            $ip = request()->ip();
            $flag = $verify_code_model->addVerifyCode(array(
                'verify_code_type' => 6,
                'verify_code' => $verify_code,
                'verify_code_user_type' => 1,
                'verify_code_user_id' => $this->member_info['member_id'],
                'verify_code_user_name' => $this->member_info['member_name'],
                'verify_code_add_time' => TIMESTAMP,
                'verify_code_ip' => $ip,
            ));
            if (!$flag) {
                output_error(lang('system_error'));
            }
            output_data(array('state' => 'true', 'msg' => lang('verification_code_has_been_sent')));
        } else {
            output_error(isset($result['message']) ? $result['message'] : lang('verification_code_sending_failed') );
        }
    }

    /**
     * 更改绑定手机 第三步 - 验证短信码
     */
    public function modify_mobile_step3()
    {
        if (!$_POST['auth_code'] || !preg_match('/^\d{6}$/', $_POST['auth_code'])) {
            output_error('请正确输入短信验证码');
        }
        $model_member = Model('member');
        $member_common_info = $model_member->getMemberCommonInfo(array('member_id' => $this->member_info['member_id']));
        if (empty($member_common_info) || !is_array($member_common_info)) {
            output_error('验证失败');
        }
        if (TIMESTAMP - $member_common_info['send_acode_time'] > 1800) {
            output_error('验证码已失效，请重新获取');
        }
        if ($member_common_info['auth_code_check_times'] > 3) {
            output_error('输入错误次数过多，请重新获取');
        }
        if ($member_common_info['auth_code'] != $_POST['auth_code']) {
            $update_data = array();
            $update_data['auth_code_check_times'] = array('exp', 'auth_code_check_times+1');
            $update = $model_member->editMemberCommon($update_data, array('member_id' => $this->member_info['member_id']));
            if (!$update) {
                output_error('系统发生错误1',['code'=>'']);
            }
            output_error('验证失败',['code'=>'']);
        }

        $data = array();
        $data['auth_code'] = '';
        $data['send_acode_time'] = 0;
        $data['auth_code_check_times'] = 0;
        $update = $model_member->editMemberCommon($data, array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误2',['code'=>'']);
        }
        $data = array();
        $data['member_mobile'] = '';
        $data['member_mobilebind'] = 0;
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), $data);
        if (!$update) {
            output_error('系统发生错误3',['code'=>'']);
        }
        output_data('1');
    }

    /**
     * 更改密码 第三步 - 验证短信码
     */
    public function modify_password_step3()
    {
        $this->_modify_pwd_check_vcode();
    }

    /**
     * 更改支付密码 第三步 - 验证短信码
     */
    public function modify_paypwd_step3()
    {
        $this->_modify_pwd_check_vcode();
    }

    public function _modify_pwd_check_vcode()
    {
        if (!$_POST['auth_code'] || !preg_match('/^\d{6}$/', $_POST['auth_code'])) {
            output_error('请正确输入短信验证码',['code'=>'']);
        }
        $model_member = Model('member');
        $member_common_info = $model_member->getMemberCommonInfo(array('member_id' => $this->member_info['member_id']));
        if (empty($member_common_info) || !is_array($member_common_info)) {
            output_error('验证失败',['code'=>'']);
        }
        if (TIMESTAMP - $member_common_info['send_acode_time'] > 1800) {
            output_error('验证码已失效，请重新获取');
        }
        if ($member_common_info['auth_code_check_times'] > 3) {
            output_error('输入错误次数过多，请重新获取');
        }
        if ($member_common_info['auth_code'] != $_POST['auth_code']) {
            $data = array();
            $update_data['auth_code_check_times'] = array('exp', 'auth_code_check_times+1');
            $update = $model_member->editMemberCommon($update_data, array('member_id' => $this->member_info['member_id']));
            if (!$update) {
                output_error('系统发生错误a');
            }
            output_error('验证失败');
        }

        $data = array();
        $data['auth_code'] = '';
        $data['send_acode_time'] = 0;
        $data['auth_code_check_times'] = 0;
        $update = $model_member->editMemberCommon($data, array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误b');
        }

        //更改密码授权
        $update = $model_member->editMemberCommon(array('auth_modify_pwd_time' => TIMESTAMP), array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误c',['code'=>'']);
        }

        output_data('1');
    }

    /**
     * 更改密码 第四步 - 检查是否有权修改密码
     */
    public function modify_password_step4()
    {
        $this->_modify_password_limit_check();
        output_data('1');
    }

    /**
     * 更改支付密码 第四步 - 检查是否有权修改密码
     */
    public function modify_paypwd_step4()
    {
        $this->_modify_pwd_limit_check();
        output_data('1');
    }

    private function _modify_pwd_limit_check()
    {   
        $verify_code = input('post.auth_code');
        $validate_data = array(
            'verify_code' => $verify_code,
        );
        $verify_code_validate = validate('verify_code');
        if (!$verify_code_validate->scene('verify_code_search')->check($validate_data)) {
            output_error($verify_code_validate->getError());
        }
        $verify_code_model = model('verify_code');
        $vali = $verify_code_model->getVerifyCodeInfo(array(
            'verify_code_type' => 6, 
            'verify_code_user_type' => 1, 
            'verify_code_user_id' => $this->member_info['member_id'], 
            'verify_code' => $verify_code, 
            'verify_code_add_time' => array('>', TIMESTAMP - VERIFY_CODE_INVALIDE_MINUTE * 1800)
        ));
        
        if (!$vali) {
            $condition = array();
            $condition['smslog_phone'] = $this->member_info['member_mobile'];
            $condition['smslog_captcha'] = $verify_code;
            $condition['smslog_type'] = 6;
            $smslog_model = model('smslog');
            $sms_log = $smslog_model->getSmsInfo($condition);
            if (empty($sms_log) || ($sms_log['smslog_smstime'] < TIMESTAMP - VERIFY_CODE_INVALIDE_MINUTE*1800)) {//半小时内进行验证为有效
                output_error(lang('validation_fails'));
            }
            
        }
        //身份验证后，需要在30分钟内完成修改密码操作
        $model_member = Model('member');

        $data = array(
            'password' => input('post.password'),
            'confirm_password' => input('post.confirm_password'),
        );
        $membersecurity_validate = validate('membersecurity');
        if (!$membersecurity_validate->scene('modify_paypwd')->check($data)) {
            output_error($membersecurity_validate->getError());
        }
        if ($data['password'] != $data['confirm_password']) {
            output_error(lang('two_password_inconsistencies'));
        }
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), array('member_paypwd' => md5($data['password'])));
        $message = $update ? lang('password_set_successfully') : lang('password_setting_failed');
        
        if ($update) {
            output_data(['state'=>$update,'msg'=>$message]);
        } else {
            output_data($message);
        }

    }
    private function _modify_password_limit_check()
    {
        $verify_code = input('post.auth_code');
        $validate_data = array(
            'verify_code' => $verify_code,
        );
        $verify_code_validate = validate('verify_code');
        if (!$verify_code_validate->scene('verify_code_search')->check($validate_data)) {
            output_error($verify_code_validate->getError());
        }
        $verify_code_model = model('verify_code');
        $vali = $verify_code_model->getVerifyCodeInfo(array('verify_code_type' => 6, 'verify_code_user_type' => 1, 'verify_code_user_id' => $this->member_info['member_id'], 'verify_code' => $verify_code, 'verify_code_add_time' => array('<', TIMESTAMP - VERIFY_CODE_INVALIDE_MINUTE * 1800)));
        
        if (!$vali) {
            $condition = array();
            $condition['smslog_phone'] = $this->member_info['member_mobile'];
            $condition['smslog_captcha'] = $verify_code;
            $condition['smslog_type'] = 6;
            $smslog_model = model('smslog');
            $sms_log = $smslog_model->getSmsInfo($condition);
            if (empty($sms_log) || ($sms_log['smslog_smstime'] < TIMESTAMP - 1800)) {//半小时内进行验证为有效
                output_error(lang('validation_fails'));
            }
            
        }
        //身份验证后，需要在30分钟内完成修改密码操作
        $model_member = Model('member');

        $data = array(
            'password' => input('post.password'),
            'confirm_password' => input('post.confirm_password'),
        );
        // $membersecurity_validate = validate('membersecurity');
        // if (!$membersecurity_validate->scene('modify_paypwd')->check($data)) {
        //     output_error($membersecurity_validate->getError());
        // }
        if ($data['password'] != $data['confirm_password']) {
            output_error(lang('two_password_inconsistencies'));
        }
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), array('member_password' => md5($data['password'])));
        $message = $update ? lang('password_set_successfully') : lang('password_setting_failed');

        if ($update) {
            output_data(['state'=>$update==1?true:false,'msg'=>$message]);
        } else {
            output_data($message);
        }

    }

    /**
     * 更改密码 第五步 - 保存新密码到数据库
     */
    public function modify_password_step5()
    {

        if (!$_POST['password'] || !$_POST['password1'] || $_POST['password'] != $_POST['password1']) {
            output_error('提交数据错误',['code'=>'']);
        }

        //身份验证后，需要在30分钟内完成修改密码操作
        $this->_modify_pwd_limit_check();

        $model_member = Model('member');

        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), array('member_password' => md5($_POST['password'])));
        if (!$update) {
            output_error('密码修改失败',['code'=>'']);
        }

        $update = $model_member->editMemberCommon(array('auth_modify_pwd_time' => '0'), array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误',['code'=>'']);
        }
        output_data('1');
    }

    /**
     * 更改支付密码 第五步 - 保存新密码到数据库
     */
    public function modify_paypwd_step5()
    {

        if (!$_POST['password'] || !$_POST['password1'] || $_POST['password'] != $_POST['password1']) {
            output_error('提交数据错误',['code'=>'']);
        }

        //身份验证后，需要在30分钟内完成修改密码操作
        $this->_modify_pwd_limit_check();

        $model_member = Model('member');
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), array('member_paypwd' => md5($_POST['password'])));
        if (!$update) {
            output_error('密码修改失败',['code'=>'']);
        }

        $update = $model_member->editMemberCommon(array('auth_modify_pwd_time' => '0'), array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误',['code'=>'']);
        }
        output_data('1');
    }

    /**
     * 验证输入支付密码是否正确
     */
    public function check_paypwd()
    {
        if (!$_POST['password']) {
            output_error('未输入支付密码',['code'=>'']);
        }
        /*if (!preg_match('/^\w{4}$/', $_POST['captcha']) || !captcha_check($_POST['codekey'], $_POST['captcha'])) {
            output_error('验证码错误',['code'=>'']);
        }*/
        if (md5($_POST['password']) != $this->member_info['member_paypwd']) {
            output_error('支付密码输入不正确',['code'=>'']);
        }

        $model_member = Model('member');
        $data = array();
        $data['member_mobile'] = '';
        $data['member_mobilebind'] = 0;
        $update = $model_member->editMember(array('member_id' => $this->member_info['member_id']), $data);
        if (!$update) {
            output_error('系统发生错误',['code'=>'']);
        }
        //授权绑定新手机
        $update = $model_member->editMemberCommon(array('auth_modify_pwd_time' => TIMESTAMP), array('member_id' => $this->member_info['member_id']));
        if (!$update) {
            output_error('系统发生错误',['code'=>'']);
        }
        output_data('1');
    }
}