<?php

namespace app\mobile\controller;



/**
 * ============================================================================
 
 * ============================================================================
 * 控制器
 */
use think\Lang;

class Membermessage extends MobileMember
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Lang::load(APP_PATH . 'home/lang/'.config('default_lang').'/membermessage.lang.php');
    }

    /**
     * 系统站内信列表
     *
     * @param
     * @return
     */
    public function systemmsg()
    {
        $message_model = model('message');

        $message_array = $message_model->getMessageList(array('from_member_id' => '0', 'message_type' => '1', 'to_member_id' => $this->member_info['member_id'], 'no_del_member_id' => $this->member_info['member_id']), 10);
        if (!empty($message_array) && is_array($message_array)) {
            foreach ($message_array as $k => $v) {
                $v['message_open'] = '0';
                $message_array[$k]['times']=date('Y-m-d H:i:s',$v['message_time']);
                if (!empty($v['read_member_id'])) {
                    $tmp_readid_arr = explode(',', $v['read_member_id']);
                    if (in_array($this->member_info['member_id'], $tmp_readid_arr)) {
                        $v['message_open'] = '1';
                    }
                }
                $v['from_member_name'] = lang('home_message_system_message');
                $message_array[$k] = $v;
            }
        }
        output_data($message_array);

    }

}